# -*- coding: utf-8 -*-
"""Clustering_K_Mean_Roman (5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SsXmO-_0e0nfcBkIGWj6sNahuR2F1Kwr
"""

# ===============================
# 1. Upload Dataset
# ===============================
from google.colab import files
import pandas as pd

uploaded = files.upload()  # Upload your dataset
filename = list(uploaded.keys())[0]

# ===============================
# 2. Load CSV
# ===============================
df = pd.read_csv(filename)

print("Original dataset shape:", df.shape)

# ===============================
# 3. Remove rows with missing Location
# ===============================
df = df.dropna(subset=['Location'])

print("After removing missing Location:", df.shape)

# ===============================
# 4. Split Location into Latitude & Longitude
# ===============================
df[['Latitude', 'Longitude']] = df['Location'].str.split(",", expand=True)

# Convert to numeric
df['Latitude'] = pd.to_numeric(df['Latitude'], errors='coerce')
df['Longitude'] = pd.to_numeric(df['Longitude'], errors='coerce')

# ===============================
# 5. Save Cleaned File
# ===============================
cleaned_filename = "roman_dataset_clean.csv"
df.to_csv(cleaned_filename, index=False)

print("\n✅ Cleaned dataset saved as", cleaned_filename)
print(df.head())

from google.colab import files

# Download the cleaned dataset
files.download("roman_dataset_clean.csv")

import pandas as pd

# Load the Roman dataset
df = pd.read_csv("roman_dataset_clean.csv")

# Drop the Location column
df = df.drop(columns=["Location"], errors="ignore")

# Save updated dataset
final_filename = "roman_dataset_final.csv"
df.to_csv(final_filename, index=False)

print("✅ Roman dataset cleaned and saved as", final_filename)
print(df.head())

from google.colab import files

files.download("roman_dataset_final.csv")

# ===============================
# 1. Import libraries
# ===============================
import pandas as pd
from sklearn.preprocessing import StandardScaler

# ===============================
# 2. Load the Roman dataset
# ===============================
df_roman = pd.read_csv("roman_dataset_final.csv")

print("Original shape:", df_roman.shape)
print(df_roman[["Latitude", "Longitude"]].head())

# ===============================
# 3. Feature selection (only Latitude & Longitude)
# ===============================
X = df_roman[["Latitude", "Longitude"]]

# ===============================
# 4. Standardize coordinates
# ===============================
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Add scaled values back into dataframe
df_roman["Latitude_scaled"] = X_scaled[:, 0]
df_roman["Longitude_scaled"] = X_scaled[:, 1]

print("\nScaled coordinates (first 5 rows):")
print(df_roman[["Latitude_scaled", "Longitude_scaled"]].head())

# ===============================
# 5. Save scaled dataset
# ===============================
df_roman.to_csv("roman_dataset_with_scaled.csv", index=False)
print("\n✅ Scaled Roman dataset saved as roman_dataset_with_scaled.csv")

pip install OSGridConverter

# 0. Install dependencies
!pip install OSGridConverter geopandas shapely -q

# ===============================
# Preprocessing Archaeological Sites in Colab (UK GridRef)
# ===============================


# 1. Upload CSV
from google.colab import files
import pandas as pd
import re
from OSGridConverter import grid2latlong
import geopandas as gpd
from shapely.geometry import Point

uploaded = files.upload()  # This will prompt you to select your CSV file

# Get the uploaded file path
file_path = list(uploaded.keys())[0]  # automatically takes the uploaded file
df = pd.read_csv(file_path)
print(f"✅ Loaded dataset with {len(df)} rows")

# 2. Extract Grid Ref (robust for your dataset)
def extract_grid_ref(text):
    text = str(text)
    match = re.search(r'Grid Ref:([A-Z]{2}\d{6,10})', text)
    if match:
        return match.group(1)
    else:
        return None

df['GridRef'] = df['Description'].fillna('') + ';' + df['Location'].fillna('')
df['GridRef'] = df['GridRef'].apply(extract_grid_ref)
print("Sample extracted GridRefs:")
print(df[['Description','GridRef']].head(10))

# 3. Convert GridRef to lat/long
def gridref_to_latlong(gridref):
    if not gridref:
        return None, None
    try:
        ll = grid2latlong(gridref)
        return ll.longitude, ll.latitude
    except Exception:
        return None, None

df[['Longitude','Latitude']] = df['GridRef'].apply(
    lambda x: pd.Series(gridref_to_latlong(x))
)

# 4. Drop rows with missing coordinates
df_clean = df.dropna(subset=['Longitude','Latitude']).copy()
print(f"✅ Cleaned dataset has {len(df_clean)} rows")

# 5. Save cleaned dataset
cleaned_file = "archaeology_dataset_cleaned.csv"
df_clean.to_csv(cleaned_file,index=False)
print(f"✅ Cleaned dataset saved as {cleaned_file}")

# 6. Create GeoDataFrame for plotting or clustering
gdf = gpd.GeoDataFrame(
    df_clean,
    geometry=[Point(xy) for xy in zip(df_clean['Longitude'],df_clean['Latitude'])],
    crs="EPSG:4326"
)
print("✅ GeoDataFrame ready for plotting or clustering")
gdf.head()

from google.colab import files

# Download the cleaned CSV
files.download("archaeology_dataset_cleaned.csv")

# ===============================
# 1. Import libraries
# ===============================
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# ===============================
# 2. Load the scaled Roman dataset
# ===============================
df_roman = pd.read_csv("roman_dataset_with_scaled.csv")

# Use only scaled Latitude and Longitude
X = df_roman[["Latitude_scaled", "Longitude_scaled"]]

# ===============================
# 3. Elbow Method
# ===============================
inertia = []
K_range = range(1, 16)  # Try 1 to 15 clusters

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X)
    inertia.append(kmeans.inertia_)

# ===============================
# 4. Plot Elbow Curve
# ===============================
plt.figure(figsize=(8, 5))
plt.plot(K_range, inertia, marker="o")
plt.xlabel("Number of clusters (k)")
plt.ylabel("Inertia (WCSS)")
plt.title("Elbow Method for Roman Dataset")
plt.grid(True)
plt.show()

import pandas as pd
from sklearn.cluster import KMeans

# ===============================
# 1. Load the scaled Roman dataset
# ===============================
df = pd.read_csv("roman_dataset_with_scaled.csv")

# ===============================
# 2. Run KMeans with k=5
# ===============================
X = df[["Latitude_scaled", "Longitude_scaled"]]

kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
df["Cluster"] = kmeans.fit_predict(X)

# ===============================
# 3. Save updated dataset
# ===============================
df.to_csv("roman_dataset_with_clusters.csv", index=False)
print("✅ Clustering complete! Saved as roman_dataset_with_clusters.csv")

# Quick check
print(df.head())

!pip install contextily geopandas shapely

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from shapely.geometry import Point
import contextily as ctx

# ===============================
# 1. Load dataset
# ===============================

df = pd.read_csv("roman_dataset_with_scaled.csv")

# ===============================
# 2. Run KMeans with k=5
# ===============================
X = df[["Latitude_scaled", "Longitude_scaled"]]
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
df["Cluster"] = kmeans.fit_predict(X)

# ===============================
# 3. Convert to GeoDataFrame (real coordinates)
# ===============================
gdf = gpd.GeoDataFrame(
    df,
    geometry=[Point(xy) for xy in zip(df["Longitude"], df["Latitude"])],
    crs="EPSG:4326"   # WGS84 coordinate system
)

# ===============================
# 4. Plot clusters on real-world map
# ===============================
fig, ax = plt.subplots(figsize=(10, 12))

# Plot clusters
gdf.plot(ax=ax, column="Cluster", cmap="tab10", markersize=10, alpha=0.7, legend=True)

# Add basemap (world map in Web Mercator projection)
ctx.add_basemap(ax, source=ctx.providers.OpenStreetMap.Mapnik, crs=gdf.crs)

ax.set_title("Roman Clusters in Europe (k=5)", fontsize=14)
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")
plt.show()

# ===============================
# 5. Save clustered dataset
# ===============================
df.to_csv("roman_dataset_with_clusters.csv", index=False)
print("✅ Roman clustered dataset saved as roman_dataset_with_clusters.csv")

"""# **New Correct Code**"""

# ============================================================
# 🔵 ROMAN SITES — FULL SEPARATE WORKING CODE
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt
import re
from pyproj import Transformer
from google.colab import files

# ============================
# 1. Upload CSV
# ============================
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)
print("Dataset loaded for ROMAN:", filename)


# ============================================================
# 2. Convert UK Grid Reference (NO external libs)
# ============================================================

grid_letters = {
    "A": (0, 4), "B": (1, 4), "C": (2, 4), "D": (3, 4), "E": (4, 4),
    "F": (0, 3), "G": (1, 3), "H": (2, 3), "J": (3, 3), "K": (4, 3),
    "L": (0, 2), "M": (1, 2), "N": (2, 2), "O": (3, 2), "P": (4, 2),
    "Q": (0, 1), "R": (1, 1), "S": (2, 1), "T": (3, 1), "U": (4, 1),
    "V": (0, 0), "W": (1, 0), "X": (2, 0), "Y": (3, 0), "Z": (4, 0),
}

def gridref_to_bng(gr):
    gr = gr.strip().upper().replace(" ", "")

    l1, l2 = gr[0], gr[1]
    e100, n100 = grid_letters[l1]
    e10, n10 = grid_letters[l2]

    digits = gr[2:]
    length = len(digits) // 2

    east = int(digits[:length].ljust(5, "0"))
    north = int(digits[length:].ljust(5, "0"))

    E = e100 * 500000 + e10 * 100000 + east
    N = n100 * 500000 + n10 * 100000 + north
    return E, N


# ============================================================
# 3. Extract GridRef
# ============================================================

def extract_gridref(text):
    if pd.isna(text):
        return None
    m = re.search(r"Grid Ref:([A-Z]{2}[0-9]{6,10})", text)
    return m.group(1) if m else None

df["gridref"] = df["Location"].apply(extract_gridref)
df = df.dropna(subset=["gridref"])
print("Valid GridRefs for ROMAN:", len(df))


# ============================================================
# 4. Convert GridRef → Easting/Northing
# ============================================================

df["easting"], df["northing"] = zip(*df["gridref"].apply(gridref_to_bng))


# ============================================================
# 5. Convert BNG → Lat/Lon
# ============================================================

transformer = Transformer.from_crs(27700, 4326, always_xy=True)

def to_latlon(E, N):
    lon, lat = transformer.transform(E, N)
    return lat, lon

df["latitude"], df["longitude"] = zip(*df.apply(lambda r: to_latlon(r["easting"], r["northing"]), axis=1))


# ============================================================
# 6. FILTER ROMAN ONLY
# ============================================================

roman = df[df["PeriodSubjectIntervention"].str.contains("ROMAN", case=False, na=False)]
print("Roman sites:", len(roman))


# ============================================================
# 7. PLOT ROMAN
# ============================================================

plt.figure(figsize=(9, 10))
plt.scatter(roman["longitude"], roman["latitude"], s=20, alpha=0.7)
plt.title("Corrected Roman Archaeological Sites")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.grid(True)
plt.show()

roman.to_csv("roman_sites.csv", index=False)
files.download("roman_sites.csv")

import pandas as pd
from sklearn.metrics import silhouette_score, davies_bouldin_score

# ===============================
# 1. Load Roman dataset with clusters
# ===============================
df_roman = pd.read_csv("roman_dataset_with_clusters.csv")

# Use scaled coordinates for metrics
X = df_roman[["Latitude_scaled", "Longitude_scaled"]]
labels = df_roman["Cluster"]

# ===============================
# 2. Silhouette Score
# ===============================
silhouette = silhouette_score(X, labels)
print(f"Silhouette Score (Roman): {silhouette:.4f}")

# ===============================
# 3. Davies-Bouldin Index
# ===============================
db_index = davies_bouldin_score(X, labels)
print(f"Davies-Bouldin Index (Roman): {db_index:.4f}")

# ===============================
# 4. Cluster Counts
# ===============================
cluster_counts = df_roman["Cluster"].value_counts().sort_index()
print("\nCluster Counts (Roman):")
print(cluster_counts)

# ===============================
# 5. Save metrics to file (optional)
# ===============================
metrics = {
    "Silhouette Score": [silhouette],
    "Davies-Bouldin Index": [db_index]
}
pd.DataFrame(metrics).to_csv("roman_clustering_metrics.csv", index=False)
print("\n✅ Metrics saved as roman_clustering_metrics.csv")

# ----------------------------
# STEP 1: Upload & Prepare Data
# ----------------------------
import pandas as pd
from google.colab import files

# Upload file
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Read CSV
df = pd.read_csv(filename)

print("✅ File uploaded successfully!")
print("Dataset shape:", df.shape)
print(df.head())

# Select relevant scaled features for clustering
X = df[['Latitude_scaled', 'Longitude_scaled']].values

# ----------------------------
# STEP 2: DBSCAN Clustering + Evaluation
# ----------------------------
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score, davies_bouldin_score

# Apply DBSCAN
dbscan = DBSCAN(eps=0.3, min_samples=5)
labels = dbscan.fit_predict(X)

# Add cluster labels to DataFrame
df['Cluster'] = labels

# Compute metrics
n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
n_noise = list(labels).count(-1)

if n_clusters > 1:
    silhouette = silhouette_score(X, labels)
    db_index = davies_bouldin_score(X, labels)
else:
    silhouette = None
    db_index = None

print("\n📊 DBSCAN Results:")
print(f"Number of clusters (excluding noise): {n_clusters}")
print(f"Number of noise points: {n_noise}")
print(f"Silhouette Score: {silhouette}")
print(f"Davies–Bouldin Index: {db_index}")

# ----------------------------
# DBSCAN Parameter Tuning
# ----------------------------
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score, davies_bouldin_score
#I am checking parameters after so much wait and trying to find best parameters And then I found the 0.15, 0.45, 0.05
# Parameter grid
eps_values = np.arange(0.15, 0.45, 0.05)
min_samples_values = range(3, 9)

results = []

# Grid search for DBSCAN parameters
for eps in eps_values:
    for min_samples in min_samples_values:
        db = DBSCAN(eps=eps, min_samples=min_samples)
        labels = db.fit_predict(X)

        # Skip cases with 1 or 0 clusters
        n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
        if n_clusters < 2:
            continue

        sil_score = silhouette_score(X, labels)
        db_index = davies_bouldin_score(X, labels)
        results.append((eps, min_samples, n_clusters, sil_score, db_index))

# Convert to DataFrame
results_df = pd.DataFrame(results, columns=['eps', 'min_samples', 'clusters', 'silhouette', 'davies_bouldin'])

# Find best by silhouette
best_row = results_df.loc[results_df['silhouette'].idxmax()]

print("🏆 Best Parameters Found:")
print(f"eps = {best_row.eps}")
print(f"min_samples = {best_row.min_samples}")
print(f"Number of clusters = {best_row.clusters}")
print(f"Silhouette Score = {best_row.silhouette:.4f}")
print(f"Davies–Bouldin Index = {best_row.davies_bouldin:.4f}")

# ----------------------------
# Visualization of results
# ----------------------------
plt.figure(figsize=(8,6))
pivot_sil = results_df.pivot(index="min_samples", columns="eps", values="silhouette")
sns.heatmap(pivot_sil, annot=True, cmap="YlGnBu", fmt=".2f")
plt.title("Silhouette Score for DBSCAN Parameters")
plt.xlabel("eps")
plt.ylabel("min_samples")
plt.show()

plt.figure(figsize=(8,6))
pivot_db = results_df.pivot(index="min_samples", columns="eps", values="davies_bouldin")
sns.heatmap(pivot_db, annot=True, cmap="YlOrRd_r", fmt=".2f")
plt.title("Davies–Bouldin Index for DBSCAN Parameters")
plt.xlabel("eps")
plt.ylabel("min_samples")
plt.show()

# ----------------------------
# FINAL DBSCAN USING BEST PARAMETERS
# ----------------------------
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score, davies_bouldin_score
import matplotlib.pyplot as plt

# Best parameters from tuning
best_eps = 0.35
best_min_samples = 7

# Apply DBSCAN
dbscan_best = DBSCAN(eps=best_eps, min_samples=best_min_samples)
labels_best = dbscan_best.fit_predict(X)

# Add to dataframe
df['Cluster'] = labels_best

# Compute metrics
n_clusters = len(set(labels_best)) - (1 if -1 in labels_best else 0)
n_noise = list(labels_best).count(-1)
silhouette = silhouette_score(X, labels_best) if n_clusters > 1 else None
db_index = davies_bouldin_score(X, labels_best) if n_clusters > 1 else None

print("📊 Final DBSCAN Results (Optimized Parameters):")
print(f"eps: {best_eps}")
print(f"min_samples: {best_min_samples}")
print(f"Number of clusters (excluding noise): {n_clusters}")
print(f"Number of noise points: {n_noise}")
print(f"Silhouette Score: {silhouette:.4f}")
print(f"Davies–Bouldin Index: {db_index:.4f}")

# ----------------------------
# Visualization
# ----------------------------
plt.figure(figsize=(8,6))
unique_labels = set(labels_best)
for label in unique_labels:
    if label == -1:
        color = 'gray'
        label_name = 'Noise'
    else:
        color = plt.cm.tab10(label / max(unique_labels))
        label_name = f'Cluster {label}'
    plt.scatter(X[labels_best == label, 0], X[labels_best == label, 1],
                label=label_name, s=30, alpha=0.6, color=color)

plt.title("DBSCAN Clustering (Optimized Roman Dataset)")
plt.xlabel("Latitude_scaled")
plt.ylabel("Longitude_scaled")
plt.legend()
plt.show()

from google.colab import files

output_file = "roman_dbscan_optimized_clusters.csv"
df.to_csv(output_file, index=False)
files.download(output_file)

print("✅ Results saved and ready for download as:", output_file)

# ============================================
# PLOT UNSCALED DATASET (CHECK COORDINATES)
# ============================================

# --- 1. Upload and Read Dataset ---
from google.colab import files
import pandas as pd
import folium
from folium.plugins import MarkerCluster

# Upload CSV file
uploaded = files.upload()

# Get the uploaded filename
file_name = list(uploaded.keys())[0]

# Read CSV file
df = pd.read_csv(file_name)

# Show first few rows to confirm
print("Preview of uploaded data:")
print(df.head(), "\n")
print("Available columns:", list(df.columns))

# --- 2. Standardize Column Names ---
# Adjust column names if needed (add your actual column names here if different)
df = df.rename(columns={
    'lat': 'Latitude',
    'long': 'Longitude',
    'Lat': 'Latitude',
    'Lon': 'Longitude',
    'LON': 'Longitude',
    'LAT': 'Latitude'
})

# Check that required columns exist
if 'Latitude' not in df.columns or 'Longitude' not in df.columns:
    raise ValueError("❌ Please make sure your dataset has 'Latitude' and 'Longitude' columns.")

# --- 3. Plot Unscaled Coordinates ---
# Create UK base map
m = folium.Map(location=[54, -2], zoom_start=6, tiles='cartodb positron')

# Add marker cluster for clarity
marker_cluster = MarkerCluster().add_to(m)

# Add points to map
for _, row in df.iterrows():
    if pd.notnull(row['Latitude']) and pd.notnull(row['Longitude']):
        folium.CircleMarker(
            location=[row['Latitude'], row['Longitude']],
            radius=2,
            color='blue',
            fill=True,
            fill_opacity=0.6
        ).add_to(marker_cluster)

# Display map
print("✅ Map generated successfully. Scroll down to view it below.")
m

# ----------------------------
# ROMAN CLUSTER VISUALIZATION ON UK MAP
# ----------------------------

import pandas as pd
import folium
from folium.plugins import MarkerCluster

# === Step 1: Upload Dataset ===
from google.colab import files
uploaded = files.upload()

# Replace this with your uploaded filename
file_name = list(uploaded.keys())[0]

# === Step 2: Read Data ===
df = pd.read_csv(file_name)

# Check structure
print("✅ Dataset Loaded:", df.shape)
print(df.head())

# Ensure necessary columns exist
required_columns = ['Latitude', 'Longitude', 'Cluster']
for col in required_columns:
    if col not in df.columns:
        raise ValueError(f"Missing required column: {col}")

# === Step 3: Create Base Map ===
# Centered roughly over the UK
uk_center = [54.5, -3.5]
m = folium.Map(location=uk_center, zoom_start=6, tiles="CartoDB positron")

# === Step 4: Add Clustered Points ===
colors = [
    'red', 'blue', 'green', 'purple', 'orange', 'darkred',
    'lightred', 'beige', 'darkblue', 'darkgreen', 'cadetblue',
    'pink', 'lightblue', 'lightgreen', 'gray', 'black'
]

marker_cluster = MarkerCluster().add_to(m)

for _, row in df.iterrows():
    cluster_id = int(row['Cluster']) if row['Cluster'] != -1 else -1
    color = 'black' if cluster_id == -1 else colors[cluster_id % len(colors)]

    folium.CircleMarker(
        location=[row['Latitude'], row['Longitude']],
        radius=3,
        color=color,
        fill=True,
        fill_opacity=0.7,
        popup=f"Cluster: {cluster_id}"
    ).add_to(marker_cluster)

# === Step 5: Save and Display Map ===
map_file = "roman_clusters_on_uk_map.html"
m.save(map_file)

print(f"✅ Map saved as: {map_file}")
print("You can now download and open it in your browser.")

"""# **New Working Correct**"""

# =========================================
# 1. Upload the dataset in Google Colab
# =========================================
from google.colab import files
import pandas as pd

# Upload file
uploaded = files.upload()

# Automatically get uploaded filename
filename = list(uploaded.keys())[0]
df_raw = pd.read_csv(filename)

# Show the first few rows
df_raw.head()

# =========================================
# 2. Keep only required columns
# =========================================
required_cols = [
    "Title",
    "Description",
    "Location",
    "PeriodSubjectIntervention",
    "Indentifiers",
    "People",
    "Bibliographic References",
    "URL"
]

df = df_raw[required_cols].copy()

# Show the head and number of entries remaining
print("Number of entries:", len(df))
df.head()

# =========================================
# 3. Extract Easting & Northing from Location
# =========================================
import re
import numpy as np

def extract_coordinates(location):
    if pd.isna(location):
        return None, None

    # Find all occurrences of EPSG:27700:<number>
    matches = re.findall(r"EPSG:27700:(\d+)", location)

    if len(matches) >= 2:
        easting = int(matches[0])
        northing = int(matches[1])
        return easting, northing

    return None, None

df["easting"], df["northing"] = zip(*df["Location"].map(extract_coordinates))

# Show head and number of entries with coordinates extracted
print("Number of entries after extracting coordinates:", df.dropna(subset=["easting", "northing"]).shape[0])
df[["Title", "Location", "easting", "northing"]].head()

# =========================================
# 4. Convert BNG (EPSG:27700) to Latitude/Longitude (WGS84)
# =========================================

!pip install pyproj -q

from pyproj import Transformer

# Initialize transformer
transformer = Transformer.from_crs("EPSG:27700", "EPSG:4326", always_xy=True)

# Convert each row
def convert_to_latlon(easting, northing):
    lon, lat = transformer.transform(easting, northing)
    return lat, lon

df["latitude"], df["longitude"] = zip(*df.apply(lambda row: convert_to_latlon(row["easting"], row["northing"]), axis=1))

# Show head and number of entries after conversion
print("Number of entries after conversion:", df.dropna(subset=["latitude", "longitude"]).shape[0])
df[["Title", "easting", "northing", "latitude", "longitude"]].head()

# =========================================
# 5. Remove rows with missing Latitude or Longitude only
# =========================================

df_clean = df.dropna(subset=["latitude", "longitude"])

# Show the head and number of entries remaining
print("Number of entries after removing missing lat/lon:", len(df_clean))
df_clean.head()

# =========================================
# Save the cleaned Neolithic dataset
# =========================================

df_clean.to_csv("finalRomanAfterPreProcessing.csv", index=False)
df_clean.head()

from google.colab import files

files.download("finalRomanAfterPreProcessing.csv")

import pandas as pd
import matplotlib.pyplot as plt
import re
from pyproj import Transformer
from sklearn.cluster import DBSCAN
import numpy as np
from google.colab import files

# 1. Upload CSV
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)
print("Dataset loaded:", filename)

# 2. UK Grid Reference conversion
grid_letters = {
    "A": (0, 4), "B": (1, 4), "C": (2, 4), "D": (3, 4), "E": (4, 4),
    "F": (0, 3), "G": (1, 3), "H": (2, 3), "J": (3, 3), "K": (4, 3),
    "L": (0, 2), "M": (1, 2), "N": (2, 2), "O": (3, 2), "P": (4, 2),
    "Q": (0, 1), "R": (1, 1), "S": (2, 1), "T": (3, 1), "U": (4, 1),
    "V": (0, 0), "W": (1, 0), "X": (2, 0), "Y": (3, 0), "Z": (4, 0),
}

def gridref_to_bng(gr):
    gr = gr.strip().upper().replace(" ", "")
    l1, l2 = gr[0], gr[1]
    e100, n100 = grid_letters[l1]
    e10, n10 = grid_letters[l2]
    digits = gr[2:]
    length = len(digits) // 2
    east = int(digits[:length].ljust(5, "0"))
    north = int(digits[length:].ljust(5, "0"))
    E = e100 * 500000 + e10 * 100000 + east
    N = n100 * 500000 + n10 * 100000 + north
    return E, N

# 3. Extract GridRef from Location
def extract_gridref(text):
    if pd.isna(text):
        return None
    m = re.search(r"Grid Ref:([A-Z]{2}[0-9]{6,10})", text)
    return m.group(1) if m else None

df["gridref"] = df["Location"].apply(extract_gridref)
df = df.dropna(subset=["gridref"])
print("Valid GridRefs found:", len(df))

# 4. Convert GridRef → Easting/Northing
df["easting"], df["northing"] = zip(*df["gridref"].apply(gridref_to_bng))

# 5. Convert BNG → Lat/Lon
transformer = Transformer.from_crs(27700, 4326, always_xy=True)
def to_latlon(E, N):
    lon, lat = transformer.transform(E, N)
    return lat, lon

df["latitude"], df["longitude"] = zip(*df.apply(lambda r: to_latlon(r["easting"], r["northing"]), axis=1))

# 6. Filter Roman data only
roman = df[df["PeriodSubjectIntervention"].str.contains("ROMAN", case=False, na=False)].copy()
print("Roman sites:", len(roman))

# 7. DBSCAN clustering
coords = np.radians(roman[['latitude', 'longitude']].to_numpy())
eps_km = 1.0
eps_rad = eps_km / 6371.0
dbscan = DBSCAN(eps=eps_rad, min_samples=5, algorithm='ball_tree', metric='haversine')
clusters = dbscan.fit_predict(coords)
roman['cluster'] = clusters

n_clusters = len(set(clusters)) - (1 if -1 in clusters else 0)
print(f"Roman DBSCAN found {n_clusters} clusters")
print(roman['cluster'].value_counts())

# 8. Plot clusters
plt.figure(figsize=(10, 8))
plt.scatter(roman['longitude'], roman['latitude'], c=clusters, cmap='tab20', s=20)
plt.colorbar(label='Cluster Label')
plt.title('DBSCAN Clustering of Roman Sites')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.grid(True)
plt.show()

from google.colab import files
import pandas as pd

# Upload the final combined CSV or separate CSV files
uploaded = files.upload()

# Get the file name
filename = list(uploaded.keys())[0]
print("Dataset loaded:", filename)

# Read the dataset
df = pd.read_csv(filename)

df.head()

# ============================================================
# 🔵 ELBOW METHOD — ROMAN SITES
# ============================================================

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# 4. Clean latitude and longitude columns
df['latitude'] = pd.to_numeric(df['latitude'], errors='coerce')
df['longitude'] = pd.to_numeric(df['longitude'], errors='coerce')

# Drop rows with NaN values in latitude or longitude
df = df.dropna(subset=['latitude', 'longitude'])

# Remove rows with infinite values if any
df = df[(df['latitude'] != float('inf')) & (df['latitude'] != float('-inf'))]
df = df[(df['longitude'] != float('inf')) & (df['longitude'] != float('-inf'))]

# 5. Extract latitude and longitude as numpy array for clustering
X_roman = df[['latitude', 'longitude']].values

# 6. Elbow Method for KMeans clustering
wcss_roman = []

for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_roman)
    wcss_roman.append(kmeans.inertia_)

# 7. Plot the elbow curve
plt.figure(figsize=(8,5))
plt.plot(range(1, 11), wcss_roman, marker='o')
plt.title('Elbow Method - Roman Sites')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Within-Cluster Sum of Squares (WCSS)')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import re
from pyproj import Transformer
from sklearn.cluster import KMeans
from google.colab import files
import numpy as np

# ============================
# 1. Upload CSV for Roman data
# ============================
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)
print("Dataset loaded for ROMAN:", filename)


# ============================
# 2. Convert UK Grid Reference (NO external libs)
# ============================

grid_letters = {
    "A": (0, 4), "B": (1, 4), "C": (2, 4), "D": (3, 4), "E": (4, 4),
    "F": (0, 3), "G": (1, 3), "H": (2, 3), "J": (3, 3), "K": (4, 3),
    "L": (0, 2), "M": (1, 2), "N": (2, 2), "O": (3, 2), "P": (4, 2),
    "Q": (0, 1), "R": (1, 1), "S": (2, 1), "T": (3, 1), "U": (4, 1),
    "V": (0, 0), "W": (1, 0), "X": (2, 0), "Y": (3, 0), "Z": (4, 0),
}

def gridref_to_bng(gr):
    gr = gr.strip().upper().replace(" ", "")

    l1, l2 = gr[0], gr[1]
    e100, n100 = grid_letters[l1]
    e10, n10 = grid_letters[l2]

    digits = gr[2:]
    length = len(digits) // 2

    east = int(digits[:length].ljust(5, "0"))
    north = int(digits[length:].ljust(5, "0"))

    E = e100 * 500000 + e10 * 100000 + east
    N = n100 * 500000 + n10 * 100000 + north
    return E, N


# ============================
# 3. Extract GridRef
# ============================

def extract_gridref(text):
    if pd.isna(text):
        return None
    m = re.search(r"Grid Ref:([A-Z]{2}[0-9]{6,10})", text)
    return m.group(1) if m else None

df["gridref"] = df["Location"].apply(extract_gridref)
df = df.dropna(subset=["gridref"])
print("Valid GridRefs for ROMAN:", len(df))


# ============================
# 4. Convert GridRef → Easting/Northing
# ============================

df["easting"], df["northing"] = zip(*df["gridref"].apply(gridref_to_bng))


# ============================
# 5. Convert BNG → Lat/Lon
# ============================

transformer = Transformer.from_crs(27700, 4326, always_xy=True)

def to_latlon(E, N):
    lon, lat = transformer.transform(E, N)
    return lat, lon

df["latitude"], df["longitude"] = zip(*df.apply(lambda r: to_latlon(r["easting"], r["northing"]), axis=1))


# ============================
# 6. FILTER ROMAN ONLY
# ============================

roman = df[df["PeriodSubjectIntervention"].str.contains("ROMAN", case=False, na=False)]
print("Roman sites:", len(roman))

# Clean latitude and longitude columns
roman['latitude'] = pd.to_numeric(roman['latitude'], errors='coerce')
roman['longitude'] = pd.to_numeric(roman['longitude'], errors='coerce')

# Remove rows with NaN or infinite values
roman = roman.dropna(subset=['latitude', 'longitude'])
roman = roman[np.isfinite(roman['latitude'])]
roman = roman[np.isfinite(roman['longitude'])]

# ============================
# 7. K-MEANS CLUSTERING (k=3)
# ============================

X_roman = roman[['latitude', 'longitude']].to_numpy()

k = 3
kmeans = KMeans(n_clusters=k, random_state=42)
clusters = kmeans.fit_predict(X_roman)

roman['kmeans_cluster'] = clusters

print(f"KMeans found {len(set(clusters))} clusters")
print(roman['kmeans_cluster'].value_counts())


# ============================
# 8. PLOT ROMAN with K-Means clusters
# ============================

plt.figure(figsize=(9, 10))
scatter = plt.scatter(roman["longitude"], roman["latitude"], c=clusters, cmap='tab10', s=30, edgecolor='k', alpha=0.7)
plt.title(f"K-Means Clustering of Roman Archaeological Sites (k={k})")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.grid(True)
plt.colorbar(scatter, label='Cluster Label')
plt.show()

import pandas as pd
import re
from pyproj import Transformer
from sklearn.cluster import DBSCAN, KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score
import numpy as np
from google.colab import files

# 1. Upload CSV file
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)
print("Dataset loaded for ROMAN:", filename)

# 2. UK Grid Reference conversion setup
grid_letters = {
    "A": (0, 4), "B": (1, 4), "C": (2, 4), "D": (3, 4), "E": (4, 4),
    "F": (0, 3), "G": (1, 3), "H": (2, 3), "J": (3, 3), "K": (4, 3),
    "L": (0, 2), "M": (1, 2), "N": (2, 2), "O": (3, 2), "P": (4, 2),
    "Q": (0, 1), "R": (1, 1), "S": (2, 1), "T": (3, 1), "U": (4, 1),
    "V": (0, 0), "W": (1, 0), "X": (2, 0), "Y": (3, 0), "Z": (4, 0),
}

def gridref_to_bng(gr):
    gr = gr.strip().upper().replace(" ", "")
    l1, l2 = gr[0], gr[1]
    e100, n100 = grid_letters[l1]
    e10, n10 = grid_letters[l2]
    digits = gr[2:]
    length = len(digits) // 2
    east = int(digits[:length].ljust(5, "0"))
    north = int(digits[length:].ljust(5, "0"))
    E = e100 * 500000 + e10 * 100000 + east
    N = n100 * 500000 + n10 * 100000 + north
    return E, N

def extract_gridref(text):
    if pd.isna(text):
        return None
    m = re.search(r"Grid Ref:([A-Z]{2}[0-9]{6,10})", text)
    return m.group(1) if m else None

# 3. Extract and filter grid references
df["gridref"] = df["Location"].apply(extract_gridref)
df = df.dropna(subset=["gridref"])
print("Valid GridRefs for ROMAN:", len(df))

# 4. Convert GridRef to Easting/Northing
df["easting"], df["northing"] = zip(*df["gridref"].apply(gridref_to_bng))

# 5. Convert Easting/Northing to Lat/Lon
transformer = Transformer.from_crs(27700, 4326, always_xy=True)

def to_latlon(E, N):
    lon, lat = transformer.transform(E, N)
    return lat, lon

df["latitude"], df["longitude"] = zip(*df.apply(lambda r: to_latlon(r["easting"], r["northing"]), axis=1))

# 6. Filter Roman sites only
roman = df[df["PeriodSubjectIntervention"].str.contains("ROMAN", case=False, na=False)].copy()
print("Roman sites:", len(roman))

# Clean lat/lon and drop invalids
roman['latitude'] = pd.to_numeric(roman['latitude'], errors='coerce')
roman['longitude'] = pd.to_numeric(roman['longitude'], errors='coerce')
roman = roman.dropna(subset=['latitude', 'longitude'])
roman = roman[np.isfinite(roman['latitude'])]
roman = roman[np.isfinite(roman['longitude'])]

# Prepare data for clustering
X_roman_latlon = roman[['latitude', 'longitude']].to_numpy()

# 7. DBSCAN clustering (eps ~ 1km in radians)
coords_radians = np.radians(X_roman_latlon)
eps_km = 1.0
eps_rad = eps_km / 6371.0
dbscan = DBSCAN(eps=eps_rad, min_samples=5, algorithm='ball_tree', metric='haversine')
dbscan_labels = dbscan.fit_predict(coords_radians)
roman['dbscan_cluster'] = dbscan_labels

n_clusters_dbscan = len(set(dbscan_labels)) - (1 if -1 in dbscan_labels else 0)
print(f"Roman DBSCAN found {n_clusters_dbscan} clusters")
print(roman['dbscan_cluster'].value_counts())

# 8. K-Means clustering (k=3)
k = 3
kmeans = KMeans(n_clusters=k, random_state=42)
kmeans_labels = kmeans.fit_predict(X_roman_latlon)
roman['kmeans_cluster'] = kmeans_labels
print(f"Roman KMeans found {len(set(kmeans_labels))} clusters")
print(roman['kmeans_cluster'].value_counts())

# 9. Calculate Silhouette and Davies-Bouldin scores

from sklearn.metrics import silhouette_score, davies_bouldin_score

# For KMeans
sil_kmeans = silhouette_score(X_roman_latlon, kmeans_labels)
db_kmeans = davies_bouldin_score(X_roman_latlon, kmeans_labels)
print(f"Roman KMeans Silhouette Score: {sil_kmeans:.4f}")
print(f"Roman KMeans Davies-Bouldin Index: {db_kmeans:.4f}")

# For DBSCAN (ignore noise points labeled -1)
mask = dbscan_labels != -1
if np.sum(mask) > 0:
    sil_dbscan = silhouette_score(X_roman_latlon[mask], dbscan_labels[mask])
    db_dbscan = davies_bouldin_score(X_roman_latlon[mask], dbscan_labels[mask])
    print(f"Roman DBSCAN Silhouette Score: {sil_dbscan:.4f}")
    print(f"Roman DBSCAN Davies-Bouldin Index: {db_dbscan:.4f}")
else:
    print("No DBSCAN clusters (non-noise) found for Roman to calculate scores.")

